interface SummarizeRequest {
  content: string;
}

interface SummarizeResponse {
  mode: 'deterministic' | 'ollama' | 'gemini';
  summary: string;
  notes: string;
}

function deterministicSummary(content: string): string {
  const cleaned = content.replace(/\s+/g, ' ').trim();
  if (!cleaned) return 'No content provided.';
  const sentences = cleaned.split(/(?<=[.!?])\s+/).filter(Boolean);
  return sentences.slice(0, 4).join(' ');
}

async function callOllama(content: string): Promise<string | null> {
  const model = (globalThis as any)?.process?.env?.OLLAMA_MODEL ?? 'llama3.2';
  try {
    const response = await fetch((globalThis as any)?.process?.env?.OLLAMA_GENERATE_URL ?? 'http://127.0.0.1:11434/api/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ model, prompt: `Summarize this:\n${content}`, stream: false })
    });
    if (!response.ok) return null;
    const body = await response.json() as { response?: string };
    return body.response ?? null;
  } catch {
    return null;
  }
}

async function callGemini(content: string): Promise<string | null> {
  const key = (globalThis as any)?.process?.env?.GEMINI_API_KEY;
  if (!key) return null;
  try {
    const model = (globalThis as any)?.process?.env?.GEMINI_MODEL ?? 'gemini-1.5-flash';
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents: [{ parts: [{ text: `Summarize this:\n${content}` }] }] })
    });
    if (!response.ok) return null;
    const body = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
    return body.candidates?.[0]?.content?.parts?.[0]?.text ?? null;
  } catch {
    return null;
  }
}

export default async function handler(req: any, res: any): Promise<void> {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const body = req.body as SummarizeRequest;
  const content = typeof body?.content === 'string' ? body.content : '';

  const ollama = await callOllama(content);
  if (ollama) {
    res.status(200).json({ mode: 'ollama', summary: ollama, notes: 'Generated by local Ollama runtime.' });
    return;
  }

  const gemini = await callGemini(content);
  if (gemini) {
    res.status(200).json({ mode: 'gemini', summary: gemini, notes: 'Generated by Gemini server-side API.' });
    return;
  }

  res.status(200).json({ mode: 'deterministic', summary: deterministicSummary(content), notes: 'AI providers unavailable. Deterministic fallback used.' });
}
