export interface RouteDefinition {
  title: string;
  description: string;
  nextStep: string;
}

export const routeDefinitions: Record<string, RouteDefinition> = {
  '/home': { title: 'Command Home', description: 'Recent work, suggested actions, active jobs, and workspace snapshot.', nextStep: 'Upload or open a recent artifact to continue.' },
  '/intake': { title: 'Intake Hub', description: 'Upload dropzone and file intake overview.', nextStep: 'Start by adding a source file to the intake queue.' },
  '/intake/queue': { title: 'Upload Queue', description: 'Ingestion jobs with retry/cancel state visibility.', nextStep: 'Retry failed jobs or continue once processing completes.' },
  '/intake/library': { title: 'File Library', description: 'Source cards with grouping, filtering, and versioning controls.', nextStep: 'Tag and group source files for faster retrieval.' },
  '/intake/compare': { title: 'Version Compare', description: 'File-to-file or version-to-version comparison surface.', nextStep: 'Choose two source versions to compare changes.' },
  '/intake/merge': { title: 'Source Merge', description: 'Merge, replace, or keep-separate source workflow.', nextStep: 'Select merge strategy before downstream analysis.' },
  '/reader': { title: 'Universal Reader', description: 'Primary source reading surface with context actions.', nextStep: 'Open a source and pin key passages.' },
  '/reader/structure': { title: 'Extracted Structure', description: 'Section, block, and entity structure explorer.', nextStep: 'Review structure confidence before building outputs.' },
  '/reader/entities': { title: 'Entity Explorer', description: 'Clustered entities, terms, and metrics browser.', nextStep: 'Validate entities and map them to artifacts.' },
  '/reader/trace': { title: 'Source Trace', description: 'Evidence and source mapping panel.', nextStep: 'Link claims to source evidence before sharing.' },
  '/summary': { title: 'Deep Summary', description: 'Layered summary hub across facts and interpretation.', nextStep: 'Generate a draft then refine by audience.' },
  '/summary/insights': { title: 'Insights', description: 'Risks, gaps, pros/cons, and recommendations lens.', nextStep: 'Promote high-confidence insights into action items.' },
  '/summary/validation': { title: 'Confidence / Validation', description: 'Readiness and confidence verification surface.', nextStep: 'Resolve low-confidence items before export.' },
  '/docs': { title: 'Smart Docs', description: 'Document workspace for source-backed drafting.', nextStep: 'Create a new document from extracted structure.' },
  '/docs/[docId]': { title: 'Document Editor', description: 'Active document editing and evidence rails.', nextStep: 'Continue writing and attach supporting sources.' },
  '/sheets': { title: 'Smart Sheets', description: 'Spreadsheet workspace for modeled data.', nextStep: 'Import or create a sheet for operational tracking.' },
  '/sheets/[sheetId]': { title: 'Sheet Editor', description: 'Active sheet with formula and KPI views.', nextStep: 'Review anomalies and confirm formulas.' },
  '/slides': { title: 'Smart Slides', description: 'Deck workspace and storyboard alignment.', nextStep: 'Start from summary insights to build narrative.' },
  '/slides/[deckId]': { title: 'Deck Editor', description: 'Active deck editing with theme and notes.', nextStep: 'Tune slide density for presentation readiness.' },
  '/boards': { title: 'Visual Board Studio', description: 'Board gallery and composable workspace.', nextStep: 'Open a board template or create a blank board.' },
  '/boards/[boardId]': { title: 'Board Editor', description: 'Active board editing and inspector binding.', nextStep: 'Connect widgets to source artifacts and metrics.' },
  '/canvas': { title: 'Workspace Canvas', description: 'Cross-object visual workspace.', nextStep: 'Map artifacts visually to align teams.' },
  '/canvas/[canvasId]': { title: 'Canvas Editor', description: 'Active canvas with layered objects.', nextStep: 'Arrange blocks and lock finalized elements.' },
  '/flow': { title: 'Flow Studio', description: 'Graph builder for process and dependencies.', nextStep: 'Add nodes and validate sequence logic.' },
  '/flow/[flowId]': { title: 'Flow Editor', description: 'Active flow graph editing surface.', nextStep: 'Resolve validation warnings before handoff.' },
  '/mermaid': { title: 'Mermaid Studio', description: 'Code and render workspace for diagrams.', nextStep: 'Draft Mermaid syntax and validate rendering.' },
  '/mermaid/[diagramId]': { title: 'Mermaid Editor', description: 'Active Mermaid diagram editing and issue checks.', nextStep: 'Fix syntax issues and preserve last valid render.' },
  '/storyboard': { title: 'Storyboard Studio', description: 'Scene-flow planning workspace.', nextStep: 'Organize scenes before generating slides.' },
  '/storyboard/[storyId]': { title: 'Storyboard Editor', description: 'Active storyboard with inspector controls.', nextStep: 'Sequence scenes and annotate transitions.' },
  '/present/build': { title: 'Presentation Builder', description: 'Custom file-to-presentation builder workflow.', nextStep: 'Select target audience and generate outline.' },
  '/present/[presentationId]': { title: 'Presentation Editor', description: 'Active presentation editing surface.', nextStep: 'Finalize narrative and speaker notes.' },
  '/review/preview': { title: 'Preview Hub', description: 'Unified preview surface across artifacts.', nextStep: 'Preview outputs on desktop and mobile scales.' },
  '/review/present': { title: 'Presentation Mode', description: 'Fullscreen or safe present mode.', nextStep: 'Run readiness checks before live presenting.' },
  '/review/export': { title: 'Export Center', description: 'Export queue and output actions.', nextStep: 'Pick format and run export with fallback mode.' },
  '/review/history': { title: 'History / Restore', description: 'Snapshot history and restore management.', nextStep: 'Restore safely and validate after rollback.' },
  '/review/readiness': { title: 'Readiness Scores', description: 'Share-readiness evaluation and gating.', nextStep: 'Address blocking criteria before release.' },
  '/ops/issues': { title: 'Issues Center', description: 'Issue triage and ownership management.', nextStep: 'Assign owners and due dates for open issues.' },
  '/ops/raid': { title: 'RAID Center', description: 'Risk, assumption, issue, and dependency board.', nextStep: 'Capture mitigation plans for high-risk items.' },
  '/ops/decisions': { title: 'Decision Log', description: 'Decision history with rationale and trace links.', nextStep: 'Record approvals and downstream impacts.' },
  '/ops/dependencies': { title: 'Dependency Studio', description: 'Dependency graph and conflict visibility.', nextStep: 'Resolve blockers and update critical path.' },
  '/ops/changes': { title: 'Change Control', description: 'Change requests and impact evaluation.', nextStep: 'Approve, reject, or request clarification.' },
  '/ops/resources': { title: 'Resource Planner', description: 'Capacity and resource allocation workspace.', nextStep: 'Rebalance assignments against priorities.' },
  '/ops/timeline': { title: 'Timeline / Gantt', description: 'Timeline and milestone management view.', nextStep: 'Update milestone risk status for leadership.' },
  '/ops/budget': { title: 'Budget / Impact', description: 'Budget tracking and impact analysis.', nextStep: 'Review variance and annotate corrective actions.' },
  '/ops/approvals': { title: 'Approval Center', description: 'Approval queue and policy controls.', nextStep: 'Advance pending approvals with trace evidence.' },
  '/ops/meetings': { title: 'Meeting / Action Hub', description: 'Meeting digest and action extraction surface.', nextStep: 'Convert actions into tracked work items.' },
  '/ops/releases': { title: 'Release / Environment Board', description: 'Release readiness and environment status.', nextStep: 'Verify release gates and dependency health.' },
  '/ops/system': { title: 'API / System Map', description: 'System topology and API linkage map.', nextStep: 'Validate integration paths before deployment.' },
  '/workbench/pm': { title: 'PM Ops', description: 'Project manager operational cockpit.', nextStep: 'Monitor milestones, blockers, and decisions.' },
  '/workbench/technical': { title: 'Technical Ops', description: 'Technical operations cockpit for engineering flow.', nextStep: 'Track reliability, debt, and technical risks.' },
  '/workbench/sales': { title: 'Sales Ops', description: 'Sales operations workspace with proposal alignment.', nextStep: 'Connect delivery plans to customer commitments.' },
  '/workbench/executive': { title: 'Executive Cockpit', description: 'Executive-level portfolio visibility and readiness.', nextStep: 'Review rollups and escalate critical items.' },
  '/workbench/proposal': { title: 'Proposal Workspace', description: 'Proposal drafting with evidence-backed claims.', nextStep: 'Assemble narrative and supporting proof points.' },
  '/system/ai': { title: 'AI Runtime', description: 'AI runtime state, models, and fallback controls.', nextStep: 'Confirm provider health and degraded behavior.' },
  '/system/integrations': { title: 'Integrations', description: 'Google Sign-In, Drive, and external integration status.', nextStep: 'Reconnect failed sessions and rerun sync.' },
  '/system/privacy': { title: 'Privacy / Redaction', description: 'Privacy controls, masking, and redaction checks.', nextStep: 'Run redaction audit before sharing data.' },
  '/system/settings': { title: 'Workspace Settings', description: 'Theme, brand, density, and motion configuration.', nextStep: 'Save defaults for consistent team experience.' },
  '/system/jobs': { title: 'Logs / Jobs', description: 'Background jobs, logs, and observability panel.', nextStep: 'Retry failed jobs and archive resolved alerts.' },
};
